// SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
// gen-test-client: generate standalone C test client from Wayland protocol XML

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

struct Argument {
    std::string name, type, interfaceName;
    bool allowNull = false;
};
struct Event {
    std::string name;
    int since = 1;
    std::vector<Argument> arguments;
};
struct Interface {
    std::string name;
    int version = 1;
    std::vector<Event> requests, events;
};

// ---- Minimal XML parser ----
static std::string xmlAttr(const char *line, const char *attr) {
    std::string key = std::string(attr) + "=\"";
    auto pos = std::string(line).find(key);
    if (pos == std::string::npos) return "";
    pos += key.size();
    auto end = std::string(line).find("\"", pos);
    if (end == std::string::npos) return "";
    return std::string(line).substr(pos, end - pos);
}

static bool parseProtocol(const char *path, Interface &iface) {
    FILE *f = fopen(path, "r");
    if (!f) return false;
    char line[4096];
    bool inRequest = false, inEvent = false;
    Event current;
    while (fgets(line, sizeof(line), f)) {
        std::string s(line);
        if (s.find("<!--") != std::string::npos) continue;
        if (s.find("<interface") != std::string::npos) {
            iface.name = xmlAttr(line, "name");
            iface.version = atoi(xmlAttr(line, "version").c_str());
        } else if (s.find("<request") != std::string::npos) {
            inRequest = true; inEvent = false; current = Event{};
            current.name = xmlAttr(line, "name");
            std::string since = xmlAttr(line, "since");
            current.since = since.empty() ? 1 : atoi(since.c_str());
            if (xmlAttr(line, "type") == "destructor") current.name = "__destructor";
        } else if (s.find("<event") != std::string::npos) {
            inRequest = false; inEvent = true; current = Event{};
            current.name = xmlAttr(line, "name");
        } else if (s.find("</request>") != std::string::npos || s.find("</event>") != std::string::npos) {
            if (current.name != "__destructor") {
                if (inRequest) iface.requests.push_back(current);
                else iface.events.push_back(current);
            }
            inRequest = inEvent = false;
        } else if (s.find("<arg") != std::string::npos && (inRequest || inEvent)) {
            Argument arg;
            arg.name = xmlAttr(line, "name");
            arg.type = xmlAttr(line, "type");
            arg.interfaceName = xmlAttr(line, "interface");
            arg.allowNull = xmlAttr(line, "allow-null") == "true";
            current.arguments.push_back(arg);
        }
    }
    fclose(f);
    return !iface.name.empty();
}

// ---- Code generation ----
static std::string cType(const Argument &arg) {
    if (arg.type == "uint" || arg.type == "enum") return "uint32_t";
    if (arg.type == "int") return "int32_t";
    if (arg.type == "string") return "const char *";
    if (arg.type == "fixed") return "wl_fixed_t";
    if (arg.type == "fd") return "int32_t";
    if (arg.type == "new_id" || arg.type == "object")
        return arg.interfaceName.empty() ? "struct wl_proxy *" : "struct " + arg.interfaceName + " *";
    return "void *";
}

static std::string pf(const Argument &arg) {
    if (arg.type == "uint" || arg.type == "enum") return "%u";
    if (arg.type == "int") return "%d";
    if (arg.type == "string") return "%s";
    return "?";
}

static std::string pv(const Argument &arg) {
    if (arg.type == "string") return arg.name + " ? " + arg.name + " : \"(null)\"";
    return arg.name;
}

void generateClient(const Interface &iface, const std::string &basename, FILE *out) {
    fprintf(out, "// Auto-generated by gen-test-client\n\n");
    fprintf(out, "#include \"wayland-%s-client-protocol.h\"\n", basename.c_str());
    fprintf(out, "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n");
    fprintf(out, "#include <wayland-client.h>\n\n");

    // Event handlers
    for (const auto &ev : iface.events) {
        fprintf(out, "static void handle_%s(void *d, struct %s *p", ev.name.c_str(), iface.name.c_str());
        for (const auto &a : ev.arguments) fprintf(out, ", %s %s", cType(a).c_str(), a.name.c_str());
        fprintf(out, ")\n{\n    (void)d; (void)p;\n    printf(\"EVENT %s", ev.name.c_str());
        for (const auto &a : ev.arguments) fprintf(out, " %s=%s", a.name.c_str(), pf(a).c_str());
        fprintf(out, "\\n\"");
        for (const auto &a : ev.arguments) fprintf(out, ", %s", pv(a).c_str());
        fprintf(out, ");\n    fflush(stdout);\n}\n\n");
    }

    fprintf(out, "static const struct %s_listener test_listener = {\n", iface.name.c_str());
    for (const auto &ev : iface.events)
        fprintf(out, "    .%s = handle_%s,\n", ev.name.c_str(), ev.name.c_str());
    fprintf(out, "};\n\n");

    fprintf(out, "static void handle_global(void *d, struct wl_registry *r, uint32_t n, const char *i, uint32_t v)\n{\n");
    fprintf(out, "    if (strcmp(i, %s_interface.name) == 0) {\n", iface.name.c_str());
    fprintf(out, "        struct %s **pp = (struct %s **)d;\n", iface.name.c_str(), iface.name.c_str());
    fprintf(out, "        *pp = (struct %s *)wl_registry_bind(r, n, &%s_interface, v);\n", iface.name.c_str(), iface.name.c_str());
    fprintf(out, "        if (*pp) %s_add_listener(*pp, &test_listener, NULL);\n    }\n}\n\n", iface.name.c_str());
    fprintf(out, "static void handle_global_remove(void *d, struct wl_registry *r, uint32_t n) { (void)d;(void)r;(void)n; }\n\n");
    fprintf(out, "static const struct wl_registry_listener registry_listener = { .global=handle_global, .global_remove=handle_global_remove };\n\n");

    // Request dispatch — returns consumed arg count or -1
    fprintf(out, "static int dispatch_request(struct %s *p, const char *name, int argc, char **argv)\n{\n", iface.name.c_str());
    for (const auto &req : iface.requests) {
        if (req.name == "__destructor") continue;
        fprintf(out, "    if (strcmp(name,\"%s\")==0) {\n", req.name.c_str());
        int n = (int)req.arguments.size();
        fprintf(out, "        if (argc<%d) { fprintf(stderr,\"%%s expects %d args\\n\",name); return -1; }\n", n, n);
        for (int i = 0; i < n; i++) {
            const auto &a = req.arguments[i];
            if (a.type == "uint" || a.type == "enum")
                fprintf(out, "        uint32_t a_%s=(uint32_t)strtoul(argv[%d],NULL,10);\n", a.name.c_str(), i);
            else if (a.type == "int")
                fprintf(out, "        int32_t a_%s=(int32_t)strtol(argv[%d],NULL,10);\n", a.name.c_str(), i);
            else if (a.type == "string")
                fprintf(out, "        const char *a_%s=argv[%d];\n", a.name.c_str(), i);
        }
        fprintf(out, "        %s_%s(p", iface.name.c_str(), req.name.c_str());
        for (const auto &a : req.arguments)
            if (a.type != "new_id") fprintf(out, ",a_%s", a.name.c_str());
        fprintf(out, ");\n        return %d;\n    }\n", n);
    }
    fprintf(out, "    fprintf(stderr,\"Unknown request: %%s\\n\",name);\n    return -1;\n}\n\n");

    // main()
    fprintf(out, "int main(int argc, char **argv) {\n");
    fprintf(out, "    const char *sock=NULL;\n");
    fprintf(out, "    for (int i=1;i<argc;i++) {\n"
                 "        if (strcmp(argv[i],\"--socket\")==0&&i+1<argc) sock=argv[++i];\n"
                 "    }\n");
    fprintf(out, "    if (!sock) { fprintf(stderr,\"Usage: %%s --socket PATH [--request N ARGS...] [--roundtrip] [--checkpoint]\\n\",argv[0]); return 1; }\n");
    fprintf(out, "    struct wl_display *d=wl_display_connect(sock);\n    if(!d) return 1;\n");
    fprintf(out, "    struct wl_registry *r=wl_display_get_registry(d);\n");
    fprintf(out, "    struct %s *p=NULL;\n", iface.name.c_str());
    fprintf(out, "    wl_registry_add_listener(r,&registry_listener,&p);\n    wl_display_roundtrip(d);\n");
    fprintf(out, "    if(!p) { fprintf(stderr,\"Failed to bind %s\\n\"); return 1; }\n", iface.name.c_str());

    fprintf(out, "    int rc=0;\n"
                 "    for (int i=1;i<argc;i++) {\n"
                 "        if (strcmp(argv[i],\"--socket\")==0) { i++; continue; }\n"
                 "        if (strcmp(argv[i],\"--roundtrip\")==0) { if(wl_display_roundtrip(d)<0) { rc=1; break; } continue; }\n"
                 "        if (strcmp(argv[i],\"--checkpoint\")==0) { printf(\"CHECKPOINT\\n\"); fflush(stdout); continue; }\n"
                 "        if (strcmp(argv[i],\"--destroy\")==0) { %s_destroy(p); p=NULL; continue; }\n"
                 "        if (strcmp(argv[i],\"--request\")==0) {\n"
                 "            if (i+1>=argc) { rc=1; break; }\n"
                 "            const char *rn=argv[++i];\n"
                 "            int used=dispatch_request(p,rn,argc-i-1,&argv[i+1]);\n"
                 "            if (used<0) { rc=1; break; }\n"
                 "            i+=used;\n"
                 "            continue;\n"
                 "        }\n"
                 "    }\n",
            iface.name.c_str());

    fprintf(out, "    if(p) %s_destroy(p);\n", iface.name.c_str());
    fprintf(out, "    wl_registry_destroy(r);\n    wl_display_disconnect(d);\n    return rc;\n}\n");
}

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "Usage: %s <protocol.xml> <output.c>\n", argv[0]); return 1; }
    Interface iface;
    if (!parseProtocol(argv[1], iface)) { fprintf(stderr, "Parse failed\n"); return 1; }
    std::string path(argv[1]);
    auto s = path.rfind('/');
    std::string fn = (s != std::string::npos) ? path.substr(s+1) : path;
    auto d = fn.rfind(".xml");
    std::string base = (d != std::string::npos) ? fn.substr(0,d) : fn;
    for (auto &c : base) if (c == '_') c = '-';

    FILE *out = fopen(argv[2], "w");
    if (!out) { fprintf(stderr, "Cannot open %s\n", argv[2]); return 1; }
    generateClient(iface, base, out);
    fclose(out);
    printf("Generated %s\n", argv[2]);
    return 0;
}
